### ISSUE TITLE
Feature: Input Handling

### ISSUE THREAD

**Issue by suhas1582** [suhas1582/cpp-interactive-console#2]
# Epic Title
Feature: Input Handling

## Epic Description
Parse each line of user input. Determine if the input is valid c++ code.

## List of Tasks
- [ ] [Model the input handler system](#3)
- [ ] [Implement the required classes](#4)
- [ ] [Test the implementation](#5)
